### PR TITLE
Buttons

### LINKED ISSUE #6: **Implement Delete a class function**
- [x] Provide a list of all classes to delete from
- [x] Delete class name
- [x] Delete class attributes
- [x] Delete all relationships to and from class

Size Estimate: **4** or **5**
Actual size:  **5**
Primary: Tyler
Secondary: Chris

### PR DESCRIPTION
**Pull request by Khazarak**
Merge buttons branch into the develop branch, base functionality has been added and is working on menu options.

### CODE REVIEW

**Review by tbenz25 — DISMISSED** [review]
Looks good, just make sure documentation gets added for the menu class.

**Comment by Khazarak** [comment]
Fixed conflicts, can now be merged.

**Comment by Khazarak** [comment]
Closing until the file conflict issue is resolved.

**Review by syncronard — APPROVED** [review]
Confirmed workability.

**Pull request merged**
