### PR TITLE
Create the base project files

### LINKED ISSUE #14: Create initial project
- [x] Create base project
Size Estimate: **1**
Size Actual: **1**
Primary: @Khazarak 
Secondary: @tbenz25 
Actual Time: 30 minutes

### PR DESCRIPTION
**Pull request by tbenz25**
The files needed for the project were created, and they are now being merged with the develop branch.

### CODE REVIEW

**Comment by syncronard** [comment]
Everything is as stated

**Review by Khazarak — DISMISSED** [review]
Looks good. Approving changes.

**Review by willkill07 — CHANGES_REQUESTED** [review]
`LICENSE` shouldn't be moved
`README.md` shouldn't be moved

Otherwise, looks good to me

**Review by willkill07 — APPROVED** [review]
Looks great!

**Pull request merged**
